server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  liquibase:
    contexts: prod

app:
  jwt:
    secret: ${JWT_SECRET}
  photos:
    dir: ${PHOTOS_DIR:/data/photos}
    seed-demo: false
